#ifndef _KIN_UPGRADES_H__
#define _KIN_UPGRADES_H__


const static int MAX_KIN_POWERS = 32; //won't get up to this number, but its nice for 4 byte spacing
enum KinUpgrades
{
	POWER_AIRDASH,
	POWER_GRAV,
	POWER_BOUNCE,
	POWER_GRIND,
	POWER_TIME,
	POWER_DOUBLE_WIRES,

	//Skills + Upgrades
	SKILL_DASH_BOOST,
	SKILL_AIRDASH_BOOST,
	SKILL_GRIND_LUNGE,
	//UPGRADE_W3_CEILING_DROP_AERIAL,
	//UPGRADE_W4_SCORPION_ATTACK,
	//UPGRADE_W4_SCORPION_JUMP,
	//UPGRADE_W4_SCORPION_DOUBLE_JUMP,
	//UPGRADE_W4_SCORPION_BOUNCE,
	//UPGRADE_W5_SLOW_RESISTANCE,
	//UPGRADE_W6_BUBBLE_AIRDASH,
	//UPGRADE_W6_BUBBLE_SIZE,
	//UPGRADE_W6_EXTRA_BUBBLES_1,

	//MOVEMENT
	UPGRADE_STEEP_CLIMB,
	UPGRADE_STEEP_SLIDE,
	UPGRADE_PASSIVE_GROUND,
	UPGRADE_SPRINT,
	UPGRADE_BASE_DASH,

	//NEEDS AIRDASH
	UPGRADE_W2_BASE_AIRDASH,

	//NEEDS GRAVITY REVERSE
	UPGRADE_CEILING_STEEP_CLIMB,
	UPGRADE_CEILING_STEEP_SLIDE,
	UPGRADE_CEILING_PASSIVE_GROUND,
	UPGRADE_CEILING_SPRINT,

	//COMBAT
	UPGRADE_DECREASE_ENEMY_DAMAGE,
	UPGRADE_INCREASE_ENEMY_REGEN,
	UPGRADE_INCREASE_ENEMY_MOMENTUM,
	UPGRADE_INCREASE_STARTING_MOMENTUM,

	//POWER_UPGRADES
	


	

	

	
	UPGRADE_Count,
};


#endif