#ifndef _KIN_UPGRADES_H__
#define _KIN_UPGRADES_H__


#include "BitField.h"

const static int MAX_KIN_POWERS = 32; //won't get up to this number, but its nice for 4 byte spacing
enum KinUpgrades
{
	POWER_AIR_DASH,
	POWER_GRAVITY_CLING,
	POWER_BOUNCE_SCORPION,
	POWER_GRIND_BALL,
	POWER_HOMING_RUSH,
	POWER_DOUBLE_WIRES,

	UPGRADE_DASH,
	UPGRADE_SPEED,
	UPGRADE_ENERGY,
	UPGRADE_COMBAT,

	//ITEM_GRENADE,
	//ITEM_SPEAR,
	//ITEM_BOOST_ARMOR,
	//ITEM_CURRENCY_ATTRACTOR,

	//Skills + Upgrades
	//SKILL_DASH_BOOST_1,
	//SKILL_AIRDASH_BOOST_1,
	//SKILL_GRIND_LUNGE_1,
	//UPGRADE_W3_CEILING_DROP_AERIAL,
	//UPGRADE_W4_SCORPION_ATTACK,
	//UPGRADE_W4_SCORPION_JUMP,
	//UPGRADE_W4_SCORPION_DOUBLE_JUMP,
	//UPGRADE_W4_SCORPION_BOUNCE,
	//UPGRADE_W5_SLOW_RESISTANCE,
	//UPGRADE_W6_BUBBLE_AIRDASH,
	//UPGRADE_W6_BUBBLE_SIZE,
	//UPGRADE_W6_EXTRA_BUBBLES_1,

	//MOVEMENT
	//UPGRADE_STEEP_CLIMB,
	//UPGRADE_STEEP_SLIDE,
	//UPGRADE_PASSIVE_GROUND,
	//UPGRADE_SPRINT,

	//COMBAT
	//UPGRADE_DECREASE_ENEMY_DAMAGE,
	//UPGRADE_INCREASE_ENEMY_REGEN,
	//UPGRADE_INCREASE_ENEMY_MOMENTUM,
	//UPGRADE_INCREASE_STARTING_MOMENTUM,

	UPGRADE_Count,
};

enum KinUpgradeEffects
{
	UE_SPEED,
	UE_REDUCED_DAMAGE,
	UE_INFINITE_HEALTH,
	UE_COUNTERHIT,
	UE_CHARGEATTACK,
	UE_FASTER_KILL,
	UE_SWORD_BEAMS,
	UE_DASH_SPEED,
	UE_DASH_BOOST,
	UE_DASH_BOOST_2,
	UE_ATTACK_THROUGH_BULLETS,
	UE_TIME_SLOW_WITH_HIGH_MOMENTUM,
	UE_INCREASE_HP_GAIN_ON_HIT,
	UE_INCREASE_STARTING_MOMENTUM,
	UE_INCREASE_STARTING_HEALTH,
	UE_INCREASE_HEALTH_REGEN_FROM_CURRENCY,
	UE_INCREASE_MOMENTUM_METER_FROM_ENEMIES,
	UE_LONGER_SURVIVAL_MODE,
	UE_AIR_DASH_UNLOCK,
	UE_AIR_DASH_BOOST,
	UE_AIR_DASH_SPEED,
	UE_AIR_DASH_BOOST_2,
	UE_GRAVITY_CLING_UNLOCK,
	UE_GRAVITY_PULL,
	UE_GRAVITY_STRONGER_PULL,
	UE_GRAVITY_CEILING_SPEED,
	UE_GRAVITY_CEILING_BLAST,
	UE_GRAVITY_CEILING_BIGGER_BLAST,
	UE_GRAVITY_PULL_REGENS_WITH_WALLJUMP,
	UE_BOUNCE_SCORPION_UNLOCK,
	UE_BOUNCE_BOOST_INCREASE,
	UE_BOUNCE_JUMP_INCREASE,
	UE_BOUNCE_DOUBLE_JUMP_INCREASE,
	UE_BOUNCE_TRIPLE_JUMP,
	UE_BOUNCE_ATTACK,
	UE_GRIND_BALL_UNLOCK,
	UE_GRIND_EXTEND_LENGTH,
	UE_GRIND_SPEED_BOOST,
	UE_GRIND_ATTACK,
	UE_GRIND_LUNGE,
	UE_HOMING_RUSH_UNLOCK,
	UE_HOMING_INCREASE_RADIUS,
	UE_HOMING_BOOST_ATTACK,
	UE_HOMING_CURRENCY_ACCELERATION_BOOST,
	UE_DOUBLE_WIRES_UNLOCK,
	UE_WIRES_INCREASED_RANGE,
	UE_WIRES_ATTACH_TO_ENEMIES,
	UE_WIRES_STUN,
	UE_WIRES_INCREASED_PULL,
	UE_Count
};

struct UpgradeLevels
{
	//0 means you dont have it, higher levels is higher level upgrades

	unsigned char upgradeLevel[UPGRADE_Count];

	UpgradeLevels();
	void Clear();
	int GetUpgradeLevel(int up); //return the level of the upgrade
	bool HasUpgradeLevel(int up, int lvl); //returns true if you have that upgrade level or higher
	void SetUpgradeLevel(int up, int lvl);
	void Set(UpgradeLevels *ul);

	bool Load(std::istream &is);
	void Save(std::ofstream &of);
	bool LoadBinary(std::istream &is);
	void SaveBinary(std::ofstream &of);
};


#endif