#ifndef __RUMBLE_TYPES_H__
#define __RUMBLE_TYPES_H__

enum RumbleTypes
{
	RUMBLE_LAND,
	RUMBLE_WALL,
	RUMBLE_CEILING,
	RUMBLE_ATTACK,
	RUMBLE_WALL_JUMP,
	RUMBLE_AIR_DASH,
	RUMBLE_AIR_DASH_BOOST,
	RUMBLE_DASH_BOOST,
	RUMBLE_HIT_ENEMY,
	RUMBLE_KILL_ENEMY,
	RUMBLE_GATE,
	RUMBLE_BOOSTER,
	RUMBLE_SCORPION_BOUNCE,
	RUMBLE_CURRENCY,
	RUMBLE_DEATH,
	RUMBLE_GRAVITY_CLING,
	RUMBLE_Count
};

#endif